version: 2
updates:
  - package-ecosystem: docker
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
    labels:
      - "Type: Maintenance"
    cooldown:
      default-days: 7
    groups:
      devcontainer:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Type: Maintenance"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Type: Maintenance"
    cooldown:
      default-days: 7
    groups:
      fiber:
        patterns:
          - "github.com/gofiber/*"
      valyala:
        patterns:
          - "github.com/valyala/*"
      test-stack:
        patterns:
          - "github.com/stretchr/testify"
          - "github.com/davecgh/go-spew"
          - "github.com/pmezard/go-difflib"
