[default.extend-words]
Buildx = "Buildx"
Codecov = "Codecov"
Lefthook = "Lefthook"
casemd = "casemd"
covermode = "covermode"
coverprofile = "coverprofile"
dbaeumer = "dbaeumer"
devcontainers = "devcontainers"
esbenp = "esbenp"
evilmartians = "evilmartians"
frontends = "frontends"
gofmt = "gofmt"
gotest = "gotest"
markdownparser = "markdownparser"
moby = "moby"
pipefail = "pipefail"
renpoto = "renpoto"
testdata = "testdata"
unittests = "unittests"