baseURL = "https://9renpoto.github.io/casemd/"
locale = "en"
title = "casemd documentation"
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.mounts]]
    source = "../docs"
    target = "content"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
