name: actionlint

on:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0
        with:
          reporter: github-pr-review
          fail_on_error: true
