name: Bump version (cron)

on:
  schedule:
    - cron: "15 3 * * TUE"

permissions:
  contents: write

jobs:
  scheduled_bump:
    uses: ./.github/workflows/bump.yml # zizmor: ignore[self-repository]
    with:
      semver: minor
